CREATE TABLE book(
	isbn		INT	NOT NULL PRIMARY KEY AUTO_INCREMENT,
	title		VARCHAR(30) NOT NULL,
	author		VARCHAR(10) NOT NULL,
	publisher	VARCHAR(30) NOT NULL,
	price		INT NOT NULL,
	description	VARCHAR(255) NULL 
);

